"""JATOS exporter for jsPsych experiments.

This module provides the JATOSExporter class for creating JATOS study packages (.jzip)
from generated jsPsych experiments.
"""

from __future__ import annotations

import json
import re
import shutil
import tempfile
import uuid
import zipfile
from datetime import datetime
from pathlib import Path

from bead.data.base import BeadBaseModel, JsonValue


class JATOSExporter(BeadBaseModel):
    """Exports jsPsych experiments as JATOS study packages (.jzip).

    A .jzip file is a ZIP archive containing:
    - study.json: JATOS metadata
    - experiment/: All experiment files (HTML, JS, CSS, data)

    Attributes
    ----------
    study_title : str
        Title of the JATOS study.
    study_description : str
        Description of the study.

    Examples
    --------
    >>> from pathlib import Path
    >>> exporter = JATOSExporter("Test Study", "A test study")
    >>> # exporter.export(Path("experiment"), Path("study.jzip"))
    """

    study_title: str
    study_description: str = ""

    def export(
        self,
        experiment_dir: Path,
        output_path: Path,
        component_title: str = "Main Experiment",
    ) -> None:
        """Create JATOS .jzip file.

        Parameters
        ----------
        experiment_dir : Path
            Directory containing experiment files (from JsPsychExperimentGenerator).
            Expected structure:
            - index.html
            - css/experiment.css
            - js/experiment.js
            - data/timeline.json
            - data/config.json
        output_path : Path
            Output path for .jzip file.
        component_title : str
            Title for the JATOS component.

        Raises
        ------
        ValueError
            If experiment_dir does not exist or is missing required files.
        FileNotFoundError
            If required experiment files are not found.

        Examples
        --------
        >>> exporter = JATOSExporter("Test Study")
        >>> exporter.export(Path("exp"), Path("study.jzip"))
        """
        if not experiment_dir.exists():
            raise ValueError(f"Experiment directory does not exist: {experiment_dir}")

        if not experiment_dir.is_dir():
            raise ValueError(f"Path is not a directory: {experiment_dir}")

        # verify required files exist
        required_files = ["index.html"]
        for file in required_files:
            if not (experiment_dir / file).exists():
                raise FileNotFoundError(
                    f"Required file not found: {experiment_dir / file}"
                )

        # create temporary directory for staging
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)

            # create study.json
            study_json = self._create_study_json(component_title)
            study_json_path = temp_path / "study.json"
            study_json_path.write_text(json.dumps(study_json, indent=2))

            # copy experiment files to temp/experiment/
            experiment_target = temp_path / "experiment"
            shutil.copytree(experiment_dir, experiment_target)

            # create .jzip file
            with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zipf:
                # add study.json
                zipf.write(study_json_path, "study.json")

                # add all experiment files
                for file_path in experiment_target.rglob("*"):
                    if file_path.is_file():
                        # archive name relative to temp_path
                        arcname = file_path.relative_to(temp_path)
                        zipf.write(file_path, arcname)

    def _create_study_json(self, component_title: str) -> dict[str, JsonValue]:
        """Create JATOS study.json structure.

        Parameters
        ----------
        component_title : str
            Title for the JATOS component.

        Returns
        -------
        dict[str, JsonValue]
            JATOS study metadata dictionary.

        Notes
        -----
        The study.json follows JATOS v3 schema format.
        """
        # generate UUIDs for study and component
        study_uuid = str(uuid.uuid4())
        component_uuid = str(uuid.uuid4())

        # sanitize title for directory name
        dir_name = self._sanitize_dirname(self.study_title)

        return {
            "version": "3",
            "data": {
                "uuid": study_uuid,
                "title": self.study_title,
                "description": self.study_description,
                "dirName": dir_name,
                "comments": f"Generated by bead {datetime.now().isoformat()}",
                "jsonData": None,
                "componentList": (
                    {
                        "uuid": component_uuid,
                        "title": component_title,
                        "htmlFilePath": "experiment/index.html",
                        "reloadable": True,
                        "active": True,
                        "comments": "",
                        "jsonData": None,
                    },
                ),
                "batchList": (),
                "groupStudy": False,
                "linearStudy": False,
                "allowPreview": True,
            },
        }

    def _sanitize_dirname(self, title: str) -> str:
        """Sanitize study title for use as directory name.

        Parameters
        ----------
        title : str
            Study title to sanitize.

        Returns
        -------
        str
            Sanitized directory name.

        Examples
        --------
        >>> exporter = JATOSExporter("My Study")
        >>> exporter._sanitize_dirname("My Study")
        'my_study'
        >>> exporter._sanitize_dirname("Study (2024)")
        'study_2024'
        """
        # convert to lowercase
        dirname = title.lower()

        # replace spaces with underscores
        dirname = dirname.replace(" ", "_")

        # remove non-alphanumeric characters (except underscores)
        dirname = re.sub(r"[^a-z0-9_]", "", dirname)

        # remove consecutive underscores
        dirname = re.sub(r"_+", "_", dirname)

        # remove leading/trailing underscores
        dirname = dirname.strip("_")

        # ensure it's not empty
        if not dirname:
            dirname = "study"

        return dirname
